// Interface automatically generated by schemas-to-ts

import { Slider } from '../../../../components/shared/interfaces/Slider';
import { Tag } from '../../../tag/content-types/tag/tag';
import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media } from '../../../../common/schemas/Media';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { Subfeature } from '../../../subfeature/content-types/subfeature/subfeature';
import { Slider_Plain } from '../../../../components/shared/interfaces/Slider';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { Subfeature_Plain } from '../../../subfeature/content-types/subfeature/subfeature';
import { Slider_NoRelations } from '../../../../components/shared/interfaces/Slider';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Feature {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    featureTitle?: string;
    slug?: string;
    featureSlider?: Slider;
    tags: { data: Tag[] };
    featureBox: IconBox[];
    seo?: Seo;
    featureMedia?: { data: Media };
    faq: Faq[];
    featureDetails?: string;
    featureBlurb?: string;
    subfeatures?: { data: Subfeature[] };
  };
}
export interface Feature_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  featureSlider?: Slider_Plain;
  tags: Tag_Plain[];
  featureBox: IconBox_Plain[];
  seo?: Seo_Plain;
  featureMedia?: Media_Plain;
  faq: Faq_Plain[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: Subfeature_Plain[];
}

export interface Feature_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  featureSlider?: Slider_NoRelations;
  tags: number[];
  featureBox: IconBox_NoRelations[];
  seo?: Seo_NoRelations;
  featureMedia?: number;
  faq: Faq_NoRelations[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: number[];
}

export interface Feature_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  featureSlider?: Slider_Plain;
  tags: AdminPanelRelationPropertyModification<Tag_Plain>;
  featureBox: IconBox_Plain[];
  seo?: Seo_Plain;
  featureMedia?: AdminPanelRelationPropertyModification<Media_Plain>;
  faq: Faq_Plain[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: AdminPanelRelationPropertyModification<Subfeature_Plain>;
}
