// Interface automatically generated by schemas-to-ts

import { Tag } from '../../../tag/content-types/tag/tag';
import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media } from '../../../../common/schemas/Media';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { Subfeature } from '../../../subfeature/content-types/subfeature/subfeature';
import { CaseStudy } from '../../../case-study/content-types/case-study/case-study';
import { NextjsComp } from '../../../../components/shared/interfaces/NextjsComp';
import { Article } from '../../../article/content-types/article/article';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { Subfeature_Plain } from '../../../subfeature/content-types/subfeature/subfeature';
import { CaseStudy_Plain } from '../../../case-study/content-types/case-study/case-study';
import { NextjsComp_Plain } from '../../../../components/shared/interfaces/NextjsComp';
import { Article_Plain } from '../../../article/content-types/article/article';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { NextjsComp_NoRelations } from '../../../../components/shared/interfaces/NextjsComp';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Feature {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    featureTitle?: string;
    slug?: string;
    tags: { data: Tag[] };
    featureBox: IconBox[];
    seo?: Seo;
    featureMedia?: { data: Media };
    faq: Faq[];
    featureDetails?: string;
    featureBlurb?: string;
    subfeatures?: { data: Subfeature[] };
    relateCaseStudy?: { data: CaseStudy[] };
    gallery?: { data: Media[] };
    nextjs?: NextjsComp;
    articles?: { data: Article[] };
    featureIcon?: any;
  };
}
export interface Feature_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  tags: Tag_Plain[];
  featureBox: IconBox_Plain[];
  seo?: Seo_Plain;
  featureMedia?: Media_Plain;
  faq: Faq_Plain[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: Subfeature_Plain[];
  relateCaseStudy?: CaseStudy_Plain[];
  gallery?: Media_Plain[];
  nextjs?: NextjsComp_Plain;
  articles?: Article_Plain[];
  featureIcon?: any;
}

export interface Feature_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  tags: number[];
  featureBox: IconBox_NoRelations[];
  seo?: Seo_NoRelations;
  featureMedia?: number;
  faq: Faq_NoRelations[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: number[];
  relateCaseStudy?: number[];
  gallery?: number[];
  nextjs?: NextjsComp_NoRelations;
  articles?: number[];
  featureIcon?: any;
}

export interface Feature_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  featureTitle?: string;
  slug?: string;
  tags: AdminPanelRelationPropertyModification<Tag_Plain>;
  featureBox: IconBox_Plain[];
  seo?: Seo_Plain;
  featureMedia?: AdminPanelRelationPropertyModification<Media_Plain>;
  faq: Faq_Plain[];
  featureDetails?: string;
  featureBlurb?: string;
  subfeatures?: AdminPanelRelationPropertyModification<Subfeature_Plain>;
  relateCaseStudy?: AdminPanelRelationPropertyModification<CaseStudy_Plain>;
  gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  nextjs?: NextjsComp_Plain;
  articles?: AdminPanelRelationPropertyModification<Article_Plain>;
  featureIcon?: any;
}
