// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas/Media';
import { Media_Plain } from '../../../../common/schemas/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Press {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    pressTitle?: string;
    pressContent?: string;
    articleURL?: string;
    articleImage?: { data: Media };
    pressID?: string;
    pubDate?: Date;
  };
}
export interface Press_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pressTitle?: string;
  pressContent?: string;
  articleURL?: string;
  articleImage?: Media_Plain;
  pressID?: string;
  pubDate?: Date;
}

export interface Press_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pressTitle?: string;
  pressContent?: string;
  articleURL?: string;
  articleImage?: number;
  pressID?: string;
  pubDate?: Date;
}

export interface Press_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pressTitle?: string;
  pressContent?: string;
  articleURL?: string;
  articleImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  pressID?: string;
  pubDate?: Date;
}
