// Interface automatically generated by schemas-to-ts

import { Feature } from '../../../feature/content-types/feature/feature';
import { Feature_Plain } from '../../../feature/content-types/feature/feature';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Subfeature {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    subFeaturetitle?: string;
    subFeatureDescription?: string;
    subFeatureExcerpt?: string;
    subFeatureIcon?: any;
    features?: { data: Feature[] };
  };
}
export interface Subfeature_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  subFeaturetitle?: string;
  subFeatureDescription?: string;
  subFeatureExcerpt?: string;
  subFeatureIcon?: any;
  features?: Feature_Plain[];
}

export interface Subfeature_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  subFeaturetitle?: string;
  subFeatureDescription?: string;
  subFeatureExcerpt?: string;
  subFeatureIcon?: any;
  features?: number[];
}

export interface Subfeature_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  subFeaturetitle?: string;
  subFeatureDescription?: string;
  subFeatureExcerpt?: string;
  subFeatureIcon?: any;
  features?: AdminPanelRelationPropertyModification<Feature_Plain>;
}
