// Interface automatically generated by schemas-to-ts

import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { StatBox } from '../../../../components/shared/interfaces/StatBox';
import { PriceBox } from '../../../../components/shared/interfaces/PriceBox';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { StatBox_Plain } from '../../../../components/shared/interfaces/StatBox';
import { PriceBox_Plain } from '../../../../components/shared/interfaces/PriceBox';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { StatBox_NoRelations } from '../../../../components/shared/interfaces/StatBox';
import { PriceBox_NoRelations } from '../../../../components/shared/interfaces/PriceBox';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface AiAgent {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    agentName?: string;
    agentSegment?: string;
    agentBlurb?: string;
    iconBox: IconBox[];
    seo?: Seo;
    faq: Faq[];
    stats: StatBox[];
    priceBox: PriceBox[];
    agentBlurb2?: string;
    agentBlurb3?: string;
    agentAvatar?: { data: Media };
  };
}
export interface AiAgent_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentName?: string;
  agentSegment?: string;
  agentBlurb?: string;
  iconBox: IconBox_Plain[];
  seo?: Seo_Plain;
  faq: Faq_Plain[];
  stats: StatBox_Plain[];
  priceBox: PriceBox_Plain[];
  agentBlurb2?: string;
  agentBlurb3?: string;
  agentAvatar?: Media_Plain;
}

export interface AiAgent_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentName?: string;
  agentSegment?: string;
  agentBlurb?: string;
  iconBox: IconBox_NoRelations[];
  seo?: Seo_NoRelations;
  faq: Faq_NoRelations[];
  stats: StatBox_NoRelations[];
  priceBox: PriceBox_NoRelations[];
  agentBlurb2?: string;
  agentBlurb3?: string;
  agentAvatar?: number;
}

export interface AiAgent_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  agentName?: string;
  agentSegment?: string;
  agentBlurb?: string;
  iconBox: IconBox_Plain[];
  seo?: Seo_Plain;
  faq: Faq_Plain[];
  stats: StatBox_Plain[];
  priceBox: PriceBox_Plain[];
  agentBlurb2?: string;
  agentBlurb3?: string;
  agentAvatar?: AdminPanelRelationPropertyModification<Media_Plain>;
}
