// Interface automatically generated by schemas-to-ts

import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { AiAgent } from '../../../ai-agent/content-types/ai-agent/ai-agent';
import { CaseStudy } from '../../../case-study/content-types/case-study/case-study';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { UseCase } from '../../../use-case/content-types/use-case/use-case';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { AiAgent_Plain } from '../../../ai-agent/content-types/ai-agent/ai-agent';
import { CaseStudy_Plain } from '../../../case-study/content-types/case-study/case-study';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { UseCase_Plain } from '../../../use-case/content-types/use-case/use-case';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Industry {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    content?: string;
    excerpt?: string;
    industryIcon?: IconBox;
    agents: { data: AiAgent[] };
    case_studies?: { data: CaseStudy[] };
    iconBox: IconBox[];
    faq: Faq[];
    seo: Seo[];
    use_cases?: { data: UseCase[] };
  };
}
export interface Industry_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  industryIcon?: IconBox_Plain;
  agents: AiAgent_Plain[];
  case_studies?: CaseStudy_Plain[];
  iconBox: IconBox_Plain[];
  faq: Faq_Plain[];
  seo: Seo_Plain[];
  use_cases?: UseCase_Plain[];
}

export interface Industry_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  industryIcon?: IconBox_NoRelations;
  agents: number[];
  case_studies?: number[];
  iconBox: IconBox_NoRelations[];
  faq: Faq_NoRelations[];
  seo: Seo_NoRelations[];
  use_cases?: number[];
}

export interface Industry_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  industryIcon?: IconBox_Plain;
  agents: AdminPanelRelationPropertyModification<AiAgent_Plain>;
  case_studies?: AdminPanelRelationPropertyModification<CaseStudy_Plain>;
  iconBox: IconBox_Plain[];
  faq: Faq_Plain[];
  seo: Seo_Plain[];
  use_cases?: AdminPanelRelationPropertyModification<UseCase_Plain>;
}
