// Interface automatically generated by schemas-to-ts

import { Feature } from '../../../feature/content-types/feature/feature';
import { Integration } from '../../../integration/content-types/integration/integration';
import { Media } from '../../../../common/schemas/Media';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Feature_Plain } from '../../../feature/content-types/feature/feature';
import { Integration_Plain } from '../../../integration/content-types/integration/integration';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    excerpt?: string;
    slug?: string;
    pubDate?: Date;
    features?: { data: Feature[] };
    integrations?: { data: Integration[] };
    screenshots?: { data: Media[] };
    content?: string;
    video?: { data: Media };
    seo?: Seo;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  features?: Feature_Plain[];
  integrations?: Integration_Plain[];
  screenshots?: Media_Plain[];
  content?: string;
  video?: Media_Plain;
  seo?: Seo_Plain;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  features?: number[];
  integrations?: number[];
  screenshots?: number[];
  content?: string;
  video?: number;
  seo?: Seo_NoRelations;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  features?: AdminPanelRelationPropertyModification<Feature_Plain>;
  integrations?: AdminPanelRelationPropertyModification<Integration_Plain>;
  screenshots?: AdminPanelRelationPropertyModification<Media_Plain>[];
  content?: string;
  video?: AdminPanelRelationPropertyModification<Media_Plain>;
  seo?: Seo_Plain;
}
