// Interface automatically generated by schemas-to-ts

export interface Faq {
  question?: string;
  answer?: string;
}
export interface Faq_Plain {
  question?: string;
  answer?: string;
}

export interface Faq_NoRelations {
  question?: string;
  answer?: string;
}

