// Interface automatically generated by schemas-to-ts

export interface IconBox {
  iconTitle?: string;
  iconDescription?: string;
  svgicon?: any;
}
export interface IconBox_Plain {
  iconTitle?: string;
  iconDescription?: string;
  svgicon?: any;
}

export interface IconBox_NoRelations {
  iconTitle?: string;
  iconDescription?: string;
  svgicon?: any;
}

