// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface ImageCaption {
  caption?: string;
  image?: { data: Media };
}
export interface ImageCaption_Plain {
  caption?: string;
  image?: Media_Plain;
}

export interface ImageCaption_NoRelations {
  caption?: string;
  image?: number;
}

