// Interface automatically generated by schemas-to-ts

export interface NextjsComp {
  form_id?: string;
  agent_id?: string;
  component_id?: string;
}
export interface NextjsComp_Plain {
  form_id?: string;
  agent_id?: string;
  component_id?: string;
}

export interface NextjsComp_NoRelations {
  form_id?: string;
  agent_id?: string;
  component_id?: string;
}

