// Interface automatically generated by schemas-to-ts

export enum Frequency {
  Monthly = 'monthly',
  Annual = 'annual',
  OneTime = 'one-time',}

export interface PriceBox {
  cost?: number;
  frequency?: Frequency;
  point1?: string;
  point2?: string;
  point3?: string;
  point4?: string;
  point5?: string;
}
export interface PriceBox_Plain {
  cost?: number;
  frequency?: Frequency;
  point1?: string;
  point2?: string;
  point3?: string;
  point4?: string;
  point5?: string;
}

export interface PriceBox_NoRelations {
  cost?: number;
  frequency?: Frequency;
  point1?: string;
  point2?: string;
  point3?: string;
  point4?: string;
  point5?: string;
}

