// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas/Media';
import { OpenGraph } from './OpenGraph';
import { Media_Plain } from '../../../common/schemas/Media';
import { OpenGraph_Plain } from './OpenGraph';
import { OpenGraph_NoRelations } from './OpenGraph';

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  metaImage: { data: Media };
  metaRobots?: string;
  canonicalURL?: string;
  metaKeywords?: string;
  ogMeta?: OpenGraph;
  structuredData?: any;
}
export interface Seo_Plain {
  metaTitle: string;
  metaDescription: string;
  metaImage: Media_Plain;
  metaRobots?: string;
  canonicalURL?: string;
  metaKeywords?: string;
  ogMeta?: OpenGraph_Plain;
  structuredData?: any;
}

export interface Seo_NoRelations {
  metaTitle: string;
  metaDescription: string;
  metaImage: number;
  metaRobots?: string;
  canonicalURL?: string;
  metaKeywords?: string;
  ogMeta?: OpenGraph_NoRelations;
  structuredData?: any;
}

