// Interface automatically generated by schemas-to-ts

export interface StatBox {
  stat?: string;
  statDesc?: string;
}
export interface StatBox_Plain {
  stat?: string;
  statDesc?: string;
}

export interface StatBox_NoRelations {
  stat?: string;
  statDesc?: string;
}

