// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Team {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    linkedin?: string;
    facebook?: string;
    instagram?: string;
    image?: { data: Media };
    bio?: string;
    teamid?: string;
  };
}
export interface Team_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  linkedin?: string;
  facebook?: string;
  instagram?: string;
  image?: Media_Plain;
  bio?: string;
  teamid?: string;
}

export interface Team_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  linkedin?: string;
  facebook?: string;
  instagram?: string;
  image?: number;
  bio?: string;
  teamid?: string;
}

export interface Team_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  linkedin?: string;
  facebook?: string;
  instagram?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  bio?: string;
  teamid?: string;
}
