// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export enum JobType {
  Internship = 'Internship',
  Temporary = 'Temporary',
  Contractor = 'Contractor',
  PartTime = 'Part-Time',
  FullTime = 'Full-Time',}
export enum Location {
  BayAreaCa = 'Bay Area, CA',
  PlanoTx = 'Plano, TX',
  Remote = 'Remote',}
export enum Department {
  Product = 'Product',
  Sales = 'Sales',
  Operations = 'Operations',
  CustomerSupport = 'Customer Support',
  Engineering = 'Engineering',
  Marketing = 'Marketing',
  Administrative = 'Administrative',
  Finance = 'Finance',}

export interface Career {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    jobTitle?: string;
    jobType?: JobType;
    slug?: string;
    roleOverview?: string;
    responsibilities?: string;
    requirements?: string;
    Location?: Location;
    seo?: Seo;
    department?: Department;
  };
}
export interface Career_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  jobType?: JobType;
  slug?: string;
  roleOverview?: string;
  responsibilities?: string;
  requirements?: string;
  Location?: Location;
  seo?: Seo_Plain;
  department?: Department;
}

export interface Career_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  jobType?: JobType;
  slug?: string;
  roleOverview?: string;
  responsibilities?: string;
  requirements?: string;
  Location?: Location;
  seo?: Seo_NoRelations;
  department?: Department;
}

export interface Career_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  jobType?: JobType;
  slug?: string;
  roleOverview?: string;
  responsibilities?: string;
  requirements?: string;
  Location?: Location;
  seo?: Seo_Plain;
  department?: Department;
}
