// Interface automatically generated by schemas-to-ts

import { Tag } from '../../../tag/content-types/tag/tag';
import { Media } from '../../../../common/schemas/Media';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { NextjsComp } from '../../../../components/shared/interfaces/NextjsComp';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { NextjsComp_Plain } from '../../../../components/shared/interfaces/NextjsComp';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { NextjsComp_NoRelations } from '../../../../components/shared/interfaces/NextjsComp';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    blogTitle?: string;
    slug?: string;
    blogExcerpt?: string;
    blogContent?: string;
    tags: { data: Tag[] };
    featuredImage?: { data: Media };
    blogSEO?: Seo;
    pubDate?: Date;
    gallery?: { data: Media[] };
    nextjs: NextjsComp[];
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  blogTitle?: string;
  slug?: string;
  blogExcerpt?: string;
  blogContent?: string;
  tags: Tag_Plain[];
  featuredImage?: Media_Plain;
  blogSEO?: Seo_Plain;
  pubDate?: Date;
  gallery?: Media_Plain[];
  nextjs: NextjsComp_Plain[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  blogTitle?: string;
  slug?: string;
  blogExcerpt?: string;
  blogContent?: string;
  tags: number[];
  featuredImage?: number;
  blogSEO?: Seo_NoRelations;
  pubDate?: Date;
  gallery?: number[];
  nextjs: NextjsComp_NoRelations[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  blogTitle?: string;
  slug?: string;
  blogExcerpt?: string;
  blogContent?: string;
  tags: AdminPanelRelationPropertyModification<Tag_Plain>;
  featuredImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  blogSEO?: Seo_Plain;
  pubDate?: Date;
  gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  nextjs: NextjsComp_Plain[];
}
