// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas/Media';
import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { StatBox } from '../../../../components/shared/interfaces/StatBox';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { AiAgent } from '../../../ai-agent/content-types/ai-agent/ai-agent';
import { Feature } from '../../../feature/content-types/feature/feature';
import { Integration } from '../../../integration/content-types/integration/integration';
import { NextjsComp } from '../../../../components/shared/interfaces/NextjsComp';
import { Media_Plain } from '../../../../common/schemas/Media';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { StatBox_Plain } from '../../../../components/shared/interfaces/StatBox';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { AiAgent_Plain } from '../../../ai-agent/content-types/ai-agent/ai-agent';
import { Feature_Plain } from '../../../feature/content-types/feature/feature';
import { Integration_Plain } from '../../../integration/content-types/integration/integration';
import { NextjsComp_Plain } from '../../../../components/shared/interfaces/NextjsComp';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { StatBox_NoRelations } from '../../../../components/shared/interfaces/StatBox';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { NextjsComp_NoRelations } from '../../../../components/shared/interfaces/NextjsComp';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface CaseStudy {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title?: string;
    excerpt?: string;
    slug?: string;
    pubDate?: Date;
    featuredImage?: { data: Media };
    introText?: string;
    bodyText?: string;
    concText?: string;
    caseIconbox: IconBox[];
    caseStats: StatBox[];
    seo?: Seo;
    relateAgents?: { data: AiAgent[] };
    relateFeature?: { data: Feature[] };
    relateIntegrations?: { data: Integration[] };
    gallery?: { data: Media[] };
    nextjs?: NextjsComp;
  };
}
export interface CaseStudy_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: Media_Plain;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseIconbox: IconBox_Plain[];
  caseStats: StatBox_Plain[];
  seo?: Seo_Plain;
  relateAgents?: AiAgent_Plain[];
  relateFeature?: Feature_Plain[];
  relateIntegrations?: Integration_Plain[];
  gallery?: Media_Plain[];
  nextjs?: NextjsComp_Plain;
}

export interface CaseStudy_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: number;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseIconbox: IconBox_NoRelations[];
  caseStats: StatBox_NoRelations[];
  seo?: Seo_NoRelations;
  relateAgents?: number[];
  relateFeature?: number[];
  relateIntegrations?: number[];
  gallery?: number[];
  nextjs?: NextjsComp_NoRelations;
}

export interface CaseStudy_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseIconbox: IconBox_Plain[];
  caseStats: StatBox_Plain[];
  seo?: Seo_Plain;
  relateAgents?: AdminPanelRelationPropertyModification<AiAgent_Plain>;
  relateFeature?: AdminPanelRelationPropertyModification<Feature_Plain>;
  relateIntegrations?: AdminPanelRelationPropertyModification<Integration_Plain>;
  gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  nextjs?: NextjsComp_Plain;
}
