// Interface automatically generated by schemas-to-ts

export interface CaseStudy {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title?: string;
    excerpt?: string;
    slug?: string;
    pubDate?: Date;
  };
}
export interface CaseStudy_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
}

export interface CaseStudy_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
}

export interface CaseStudy_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
}
