// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas/Media';
import { Slider } from '../../../../components/shared/interfaces/Slider';
import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { StatBox } from '../../../../components/shared/interfaces/StatBox';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Slider_Plain } from '../../../../components/shared/interfaces/Slider';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { StatBox_Plain } from '../../../../components/shared/interfaces/StatBox';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Slider_NoRelations } from '../../../../components/shared/interfaces/Slider';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { StatBox_NoRelations } from '../../../../components/shared/interfaces/StatBox';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface CaseStudy {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title?: string;
    excerpt?: string;
    slug?: string;
    pubDate?: Date;
    featuredImage?: { data: Media };
    introText?: string;
    bodyText?: string;
    concText?: string;
    caseSlider?: Slider;
    caseIconbox: IconBox[];
    caseStats: StatBox[];
    seo?: Seo;
  };
}
export interface CaseStudy_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: Media_Plain;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseSlider?: Slider_Plain;
  caseIconbox: IconBox_Plain[];
  caseStats: StatBox_Plain[];
  seo?: Seo_Plain;
}

export interface CaseStudy_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: number;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseSlider?: Slider_NoRelations;
  caseIconbox: IconBox_NoRelations[];
  caseStats: StatBox_NoRelations[];
  seo?: Seo_NoRelations;
}

export interface CaseStudy_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title?: string;
  excerpt?: string;
  slug?: string;
  pubDate?: Date;
  featuredImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  introText?: string;
  bodyText?: string;
  concText?: string;
  caseSlider?: Slider_Plain;
  caseIconbox: IconBox_Plain[];
  caseStats: StatBox_Plain[];
  seo?: Seo_Plain;
}
