// Interface automatically generated by schemas-to-ts

import { IconBox } from '../../../../components/shared/interfaces/IconBox';
import { Industry } from '../../../industry/content-types/industry/industry';
import { Media } from '../../../../common/schemas/Media';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { IconBox_Plain } from '../../../../components/shared/interfaces/IconBox';
import { Industry_Plain } from '../../../industry/content-types/industry/industry';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { IconBox_NoRelations } from '../../../../components/shared/interfaces/IconBox';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface UseCase {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    content?: string;
    excerpt?: string;
    useCaseIcon?: IconBox;
    industries?: { data: Industry[] };
    gallery?: { data: Media[] };
    faq: Faq[];
    seo?: Seo;
    iconBox: IconBox[];
  };
}
export interface UseCase_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  useCaseIcon?: IconBox_Plain;
  industries?: Industry_Plain[];
  gallery?: Media_Plain[];
  faq: Faq_Plain[];
  seo?: Seo_Plain;
  iconBox: IconBox_Plain[];
}

export interface UseCase_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  useCaseIcon?: IconBox_NoRelations;
  industries?: number[];
  gallery?: number[];
  faq: Faq_NoRelations[];
  seo?: Seo_NoRelations;
  iconBox: IconBox_NoRelations[];
}

export interface UseCase_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  content?: string;
  excerpt?: string;
  useCaseIcon?: IconBox_Plain;
  industries?: AdminPanelRelationPropertyModification<Industry_Plain>;
  gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  faq: Faq_Plain[];
  seo?: Seo_Plain;
  iconBox: IconBox_Plain[];
}
