// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media } from '../../../../common/schemas/Media';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { CaseStudy } from '../../../case-study/content-types/case-study/case-study';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas/Media';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { CaseStudy_Plain } from '../../../case-study/content-types/case-study/case-study';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas/AdminPanelRelationPropertyModification';

export interface Integration {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    integrationTitle?: string;
    slug?: string;
    seo?: Seo;
    integrationVideo?: { data: Media };
    faq: Faq[];
    integrationDescription?: string;
    relateCaseStudy?: { data: CaseStudy[] };
    gallery?: { data: Media[] };
    integrationIcon?: { data: Media };
  };
}
export interface Integration_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  seo?: Seo_Plain;
  integrationVideo?: Media_Plain;
  faq: Faq_Plain[];
  integrationDescription?: string;
  relateCaseStudy?: CaseStudy_Plain[];
  gallery?: Media_Plain[];
  integrationIcon?: Media_Plain;
}

export interface Integration_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  seo?: Seo_NoRelations;
  integrationVideo?: number;
  faq: Faq_NoRelations[];
  integrationDescription?: string;
  relateCaseStudy?: number[];
  gallery?: number[];
  integrationIcon?: number;
}

export interface Integration_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  seo?: Seo_Plain;
  integrationVideo?: AdminPanelRelationPropertyModification<Media_Plain>;
  faq: Faq_Plain[];
  integrationDescription?: string;
  relateCaseStudy?: AdminPanelRelationPropertyModification<CaseStudy_Plain>;
  gallery?: AdminPanelRelationPropertyModification<Media_Plain>[];
  integrationIcon?: AdminPanelRelationPropertyModification<Media_Plain>;
}
