// Interface automatically generated by schemas-to-ts

import { Slider } from '../../../../components/shared/interfaces/Slider';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Faq } from '../../../../components/shared/interfaces/Faq';
import { Slider_Plain } from '../../../../components/shared/interfaces/Slider';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Faq_Plain } from '../../../../components/shared/interfaces/Faq';
import { Slider_NoRelations } from '../../../../components/shared/interfaces/Slider';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { Faq_NoRelations } from '../../../../components/shared/interfaces/Faq';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Integration {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    integrationTitle?: string;
    slug?: string;
    integrationSlider?: Slider;
    seo?: Seo;
    integrationVideo?: { data: Media };
    faq: Faq[];
    integrationDescription?: string;
  };
}
export interface Integration_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  integrationSlider?: Slider_Plain;
  seo?: Seo_Plain;
  integrationVideo?: Media_Plain;
  faq: Faq_Plain[];
  integrationDescription?: string;
}

export interface Integration_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  integrationSlider?: Slider_NoRelations;
  seo?: Seo_NoRelations;
  integrationVideo?: number;
  faq: Faq_NoRelations[];
  integrationDescription?: string;
}

export interface Integration_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  integrationTitle?: string;
  slug?: string;
  integrationSlider?: Slider_Plain;
  seo?: Seo_Plain;
  integrationVideo?: AdminPanelRelationPropertyModification<Media_Plain>;
  faq: Faq_Plain[];
  integrationDescription?: string;
}
